version: "3"
services:
  dev:
    image: ubuntu:xenial
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - gitlocal:/gitlocal
    entrypoint:
      - /scripts/idle.sh 
  dev1:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    ports:
        - 3306:3306
    environment:
        - USER=root
    links:
        - dev2
        - dev3
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal1:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh 
  dev2:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
    ports:
      - 3307:3306
  dev3:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  compiler:
    image: jr/colcomp
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  dev4:
    image: jr/column_dev_centos
    #image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal4:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh
  dev5:
    #image: jr/column_dev_centos
    image: coldev_deb
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal4:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh
  dev6:
    image: jr/column_dev_centos
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh
  dev7:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  jdk:
    image: openjdk
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
     - /scripts/idle.sh 
volumes:
    gitlocal:    
    gitlocal1:    
    #dblocal:
    #dblocal1:
    #dblocal2:
    #dblocal3:
    #dblocal4:
    pm1:
    pm2:
    um1:
            #s1:
