version: "3"
services:
  dev:
    image: ubuntu:xenial
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - gitlocal:/gitlocal
    entrypoint:
      - /scripts/idle.sh 
  dev1:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    ports:
        - 3306:3306
    environment:
        - USER=root
    links:
        - dev2
        - dev3
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal1:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh 
  dev2:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  dev3:
    image: jr/column_dev
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  compiler:
    image: jr/colcomp
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  dev4:
    image: jr/column_dev_centos
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      #- dblocal4:/usr/local/mariadb
    entrypoint:
      - /scripts/idle.sh 
  compiler:
    image: jr/colcomp
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
    entrypoint:
      - /scripts/idle.sh 
  pm1:
    image: jr/cs-general
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - pm1:/usr/local/mariadb/columnstore/data1
    entrypoint:
      - /scripts/idle.sh 
  pm2:
    image: jr/cs-general
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - pm2:/usr/local/mariadb/columnstore/data1
    entrypoint:
      - /scripts/idle.sh 
  um1:
    image: jr/cs-general
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
      - um1:/usr/local/mariadb/columnstore
    entrypoint:
      - /scripts/idle.sh 
  single1:
    image: jr/cs-base
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
  single2:
    image: jr/cs-base
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
  single3:
    image: jr/cs-base
    cap_add:
        - SYS_PTRACE
    environment:
        - USER=root
    volumes:
      - /home/drrtuy/git:/git:rw
      - /home/drrtuy/docker:/docker:rw
      - /home/drrtuy/git/cs-docker-tools/shells:/scripts:ro
        #- s1:/usr/local/mariadb/columnstore
        #entrypoint:
        # - /scripts/idle.sh 
volumes:
    gitlocal:    
    gitlocal1:    
    #dblocal:
    #dblocal1:
    #dblocal2:
    #dblocal3:
    #dblocal4:
    pm1:
    pm2:
    um1:
            #s1:
